import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppHeader } from '@/components/AppHeader';

const sections = [{ key: 'progress', icon: 'stats-chart-outline', title: 'Progression', text: 'Scores, précision et historique.' }, { key: 'missions', icon: 'flag-outline', title: 'Missions', text: 'Objectifs quotidiens et récompenses.' }, { key: 'badges', icon: 'trophy-outline', title: 'Badges', text: 'Tes succès et collections.' }, { key: 'profile', icon: 'person-outline', title: 'Mon profil', text: 'Informations et préférences.' }] as const;
export default function SpaceScreen() { return <SafeAreaView edges={['top']} style={styles.safe}><AppHeader /><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>MON ESPACE</Text><Text style={styles.title}>Ta progression</Text><Text style={styles.subtitle}>Les rubriques sont déjà à leur place. Nous les reconstruirons une à une.</Text>{sections.map((item) => <Pressable key={item.key} onPress={() => router.push({ pathname: '/space/[section]', params: { section: item.key } })} style={styles.card}><View style={styles.icon}><Ionicons color="#11a696" name={item.icon} size={23} /></View><View style={styles.copy}><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardText}>{item.text}</Text></View><Ionicons color="#82949f" name="chevron-forward" size={20} /></Pressable>)}</ScrollView></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#f3f8f7' }, content: { padding: 20, gap: 12 }, eyebrow: { color: '#11a696', letterSpacing: 3, fontWeight: '900', fontSize: 11, marginTop: 8 }, title: { color: '#102a3e', fontSize: 34, fontWeight: '900' }, subtitle: { color: '#657984', lineHeight: 22, marginBottom: 10 }, card: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#fff', borderWidth: 1, borderColor: '#d7e8e7', borderRadius: 17, padding: 16 }, icon: { width: 44, height: 44, borderRadius: 13, backgroundColor: '#e8f7f4', alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, cardTitle: { color: '#173047', fontSize: 16, fontWeight: '900' }, cardText: { color: '#6d7e89', fontSize: 13, marginTop: 3 } });
